plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'kotlin-kapt'
}

android {
    compileSdkVersion 34
    buildToolsVersion "30.0.3"

    defaultConfig {
        applicationId "com.ctw.ctwpokedex"
        minSdkVersion 33
        targetSdkVersion 33
        versionCode 1
        versionName "1.0"
        multiDexEnabled true

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
}
dependencies {

    // Room runtime library
    implementation "androidx.room:room-runtime:2.5.1"  // Or the latest stable version you need

    // Room compiler for annotation processing (use kapt for Kotlin)
    kapt "androidx.room:room-compiler:2.5.1"  // Use the same version as room-runtime

    // Room extension for coroutines (optional, for coroutine support)
    implementation "androidx.room:room-ktx:2.5.1"  // Optional, for coroutine support

    // Room RxJava2 integration
    implementation "androidx.room:room-rxjava2:2.5.1"  // RxJava2 support

    // Room testing library (for unit tests and database tests)
    testImplementation "androidx.room:room-testing:2.5.1"  // Testing support

    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    // Ensure $kotlin_version is the latest (1.9.21)

    implementation 'androidx.core:core-ktx:1.10.0' // Updated to the latest
    implementation 'androidx.appcompat:appcompat:1.6.1' // Latest stable version
    implementation 'com.google.android.material:material:1.9.0' // Latest stable version
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4' // Latest stable version
    testImplementation 'junit:junit:4.13.2' // Latest stable version
    androidTestImplementation 'androidx.test.ext:junit:1.1.5' // Latest stable version
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1' // Latest stable version
    implementation "androidx.multidex:multidex:2.0.1" // No newer version available

// Retrofit - https://github.com/square/retrofit
    implementation "com.squareup.retrofit2:retrofit:2.10.0" // Latest stable version
    implementation "com.squareup.retrofit2:converter-gson:2.10.0" // Latest stable version
    implementation "com.squareup.retrofit2:adapter-rxjava2:2.10.0" // Latest stable version

// Glide
    implementation 'com.github.bumptech.glide:glide:4.15.0' // Latest stable version
    annotationProcessor 'com.github.bumptech.glide:compiler:4.15.0' // Latest stable version

// Rx
    implementation "io.reactivex.rxjava2:rxandroid:2.1.1" // Latest stable version

// LESSON 4
// Activity KTX
    implementation 'androidx.activity:activity-ktx:1.7.0' // Latest stable version

// Lottie
    implementation 'com.airbnb.android:lottie:5.0.3' // Latest stable version

// LESSON 5
// Mockito
    testImplementation "org.mockito:mockito-core:4.8.0" // Latest stable version

// Core Test Library
    testImplementation "androidx.test:core:1.6.0" // Latest stable version
    implementation "androidx.arch.core:core-testing:2.1.0" // Latest stable version
    testImplementation "androidx.arch.core:core-testing:2.1.0"
    // Same version for testImplementation

// JUnit Rules
    testImplementation "androidx.test:rules:1.4.0" // Latest stable version

// UI Testing
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1' // Latest stable version
    androidTestImplementation 'androidx.test:runner:1.5.0' // Latest stable version
    androidTestImplementation 'androidx.test:rules:1.5.0' // Latest stable version
    androidTestImplementation 'androidx.test.espresso:espresso-intents:3.5.1'
    // Latest stable version
    androidTestImplementation 'androidx.test.uiautomator:uiautomator:2.2.0'
    // No newer version available
}
